### ISSUE TITLE
[Question] How to install next to Windows?

### ISSUE THREAD

**Issue by grzekru** [MatMoul/archfi#103]
Is there an easy way to install next to windows with dual boot option?
Do i need to format boot partition?

My current partitions look like this:
![image](https://user-images.githubusercontent.com/5862658/77845811-01690a80-71b2-11ea-9504-8e3c6a98c098.png)

**Comment by workdowg** [comment]
I am curious also. My last attempt left me with both Windows and Arch non bootable... Is there a recommended partitioning scheme?

**Comment by MatMoul** [comment]
It's difficult to help you as is.

Archfi is a project that help you for your install but for advanced install, you need to know what you do.

I suggest you to read :
https://wiki.archlinux.org/index.php/Dual_boot_with_Windows

I don't want to rewrite all the page ;-)

**Comment by ejbolt** [comment]
If you want to install next to windows, what I've done is the following:

Shrink the windows partition
Expand the boot partition to 512 MB or 1 GB (using gparted, you'll likely
need to move partitions around before you can expand the boot partition)
Free space for your Linux install if needed, or use a separate disk
During your Archfi installation, select the EFI partition that windows uses
for the boot partition for the Linux boot partition
Continue the installation as normal.
When you reboot you should get GRUB with windows and Arch boot options

I've done this dozens of times using archfi & archdi for dual boot and it's
always worked great :) Happy to help troubleshoot

**Comment by workdowg** [comment]
So my issue was a simple one. Windows was installed in MBR (no efi). So after installing Arch I only needed to install ntfs-3g, os-prober and then mount the Windows partitions and rerun grub-mkcofig. Rereading the ArchWiki more closely helps a lot. It's been a while since I've needed to install Arch and Archfi was a big help!

**Comment by MatMoul** [comment]
Closing old issue...
