### ISSUE TITLE
Encrypted install error: "info: task systemd-udevd blocked for more than 120 seconds"

### ISSUE THREAD

**Issue by VINTX2** [MatMoul/archfi#105]
Hello,

I am trying to install Arch encrypted.
The issue is that I get these errors when I start "grub-mkconfig" at the end of archfi. Sometimes it pops through the gui, too. grub-mkconfig wont end with this errors.
I had not any issue when I installed Arch with archfi unencrypted.

This are the errors:
`INFO: task systemd-udevd:1336 blocked for more than 120 seconds`
`INFO: task dmraid:28558 blocked for more than 120 seconds`

What I have done before I go into archfi:
(partitioning with cfdisk)

cryptsetup -v -y  --cipher aes-xts-plain64 --key-size 512 --hash sha512 --iter-time 5000 --use-random --verify-passphrase luksFormat /dev/nvme0n1p2

cryptsetup open /dev/nvme0n1p2 cryptlvm

pvcreate /dev/mapper/cryptlvm
vgcreate vg /dev/mapper/cryptlvm

lvcreate -L 8G vg -n swap
lvcreate -L 32G vg -n root
lvcreate -l 100%FREE vg -n home

mkfs.ext4 /dev/vg/root
mkfs.ext4 /dev/vg/home
mkswap /dev/vg/swap

mount /dev/vg/root /mnt
mkdir /mnt/home
mount /dev/vg/home /mnt/home
swapon /dev/vg/swap

mkfs.fat -F32 /dev/nvme0n1p1
mkdir /mnt/efi
mount /dev/nvme0n1p2 /mnt/efi

**Comment by MatMoul** [comment]
Not so easy config...

Are you using the last media of Arch Linux?
Do you have the same issue when you make a manual install without archfi?

With your config you need to edit some files(mkinitcpio.conf, crypttab) and pacstrap lvm2 manualy...
But the error is very strange...
> INFO: task systemd-udevd:1336 blocked for more than 120 seconds
> INFO: task dmraid:28558 blocked for more than 120 seconds

dmraid ???

**Comment by mikail0** [comment]
I have done it manually now. I didnt know that I need to edit some files (grub, mkinitcpio.conf for example).
I think that was the issue.

Here are some nice tutorials for this:
https://wiki.archlinux.org/index.php/dm-crypt/Encrypting_an_entire_system#LUKS_on_LVM
https://gist.github.com/huntrar/e42aee630bee3295b2c671d098c81268
https://www.youtube.com/watch?v=ybvwikNlx9I

**Comment by mikail0** [comment]
I have tried it again installing it with archfi.
Now I get the first error message even at the beginning, when I try to install the kernel.

**Comment by MatMoul** [comment]
When you use archfi, all cmd are printed...
Try to find when you encouter an error.
Looking here, it seem you need to edit some files :
https://wiki.archlinux.org/index.php/Dm-crypt/System_configuration

**Comment by MatMoul** [comment]
Closing old issue...
