### ISSUE TITLE
Feature request: grub and pacstrap

### ISSUE THREAD

**Issue by Diegovsky** [MatMoul/archfi#106]
Could it be possible to let the user choose the grub-install bootloader-id option? Also, if it is a good suggestion, would installing some user-defined packages be viable? I have to resort to some hacking at the moment, where I change the tty with archfi running and install packages (drivers, etc) while everything is still mounted.

By the way, archfi saved me countless times, you've done an amazing job!

**Comment by MatMoul** [comment]
I'll test if I can add bootloader-id without making the installer to hard to use...

For user definied packages, archfi is intended to make a minimal install of arch linux.
What packages prevent you to install the base and reboot ?

**Comment by Diegovsky** [comment]
Well, this problem may or may not affect only me, but as an example: suppose I am installing arch on my notebook with only wireless connection. Ok, the drivers are working fine and I can use wifi-menu to setup my connection. The thing is, after I boot up arch (assuming I installed it using only archfi), there is no wifi-menu, so I can't exactly connect to the internet and download other things.

I'm sure letting users (optionally) install packages
while everything is still mounted will solve not only my specific problem, but others problems as well (for example drivers, editors or even base-devel).

**Comment by MatMoul** [comment]
Thanks for your return...

I'm looking for a solution for the WIFI but it's requiere many packages, need some time to find a good solution.

For user packages, it's better to use a second TTY because you have all the feature and the auto completion of commands.

For drivers, in pacstrap, I've added the choice to select linux-firmwares.
I'll perhaps add these packages :
> b43-fwcutter
> broadcom-wl
> broadcom-wl-dkms
> ipw2100-fw
> ipw2200-fw

For editor, you can now install nano and vim from the Extras menu.

Base-devel is not intended to be installed from archfi.

**Comment by Diegovsky** [comment]
Ok, but is there a way to add a feature which will drop the user in a chroot environment if they want? Then, advanced users could do their thing like mess around with files and install whatever they want. Does this sounds better?

**Comment by MatMoul** [comment]
In the past, I've tried to open a shell from my script but when exiting the shell, my script was breaked...
Perhaps a message box with the help of how to switch to an other tty...

**Comment by Diegovsky** [comment]
Well, if you want some suggestions, I would put warnings to the user so they know what can happen. Also, this option could only be available in the last screen (the one where the user can choose archdi or just reboot), so that no severe breaks happen.

**Comment by MatMoul** [comment]
Just added a new feature that can help...

Now you can launch archfi with :
sh archfi -cpl {url of your package list}
as example :
sh archfi -cpl https://raw.githubusercontent.com/MatMoul/archfi/master/samples/custompackagelist

These packages will be include and selectable after filesystems on the pacstrap step...

**Comment by Diegovsky** [comment]
Wow, thank you so much! I'm anxious to use it whenever I need to install Arch again.You rock, man!
