### ISSUE TITLE
[Feature Request] : Add Window Managers

### ISSUE THREAD

**Issue by BL4CKH47H4CK3R** [MatMoul/archfi#107]
You should add the WM's too. There are so many users who don't use a DE's

**Comment by MatMoul** [comment]
@BL4CKH47H4CK3R This is why I've made arhdi and archdi-pkg...
Archfi install only the base and a bootloader...
Archdi is here to install a DE.

**Comment by BL4CKH47H4CK3R** [comment]
You should made ArchWMi ❤️
