### ISSUE TITLE
[Bug] [EFI] Grub2 can't find mount point /boot/efi

### ISSUE THREAD

**Issue by BL4CKH47H4CK3R** [MatMoul/archfi#108]
Booted from UEFI ISO mode > fat32(efi) formatted it has not /boot/efi label. So grub2 is not installing when manually done. I have done manually its working. Didn't tried automode as I don't like huge boot size like 1gb here 33MB is more than enough :+1:

**Comment by MatMoul** [comment]
Not sure what you do...
The autopart work well.
If you use a custom partion sheme, it's possible that you need make some command on tty2
