### ISSUE TITLE
Add an option for mounting EFI partition at /boot/EFI. Sure, it may break systemd-boot but I don't care. I always use GRUB.

### ISSUE THREAD

**Issue by lan-vuhoang** [MatMoul/archfi#114]

**Comment by MatMoul** [comment]
Sorry but archfi handle 4 bootloaders and I can't break it all just for you ;)

**Comment by lan-vuhoang** [comment]
Also, Manjaro Architect says that EFI partition mounted at /boot/efi is recommended for Windows dualbooting.

**Comment by lan-vuhoang** [comment]
> Sorry but archfi handle 4 bootloaders and I can't break it all just for you ;)

Also, Manjaro Architect says that EFI partition mounted at /boot/efi is recommended for Windows dualbooting.

**Comment by MatMoul** [comment]
@lan-vuhoang Yeah but we are on ArchLinux, not Manjaro or Architect...
With archfi, you can always make your own parts with TTY2.

**Comment by lan-vuhoang** [comment]
And Manjaro was just a distro based on Arch.
It has the same pacman package management tool, identical base, identical everything.

**Comment by mirh** [comment]
Manjaro-architect *really* isn't an authority, considering it thinks GPT<==>UEFI and MBR<==>BIOS. 

https://archived.forum.manjaro.org/t/ideas-for-manjaro-architect/28634/4
Also, the only provided reason /boot/efi is preferable is the still-super-vague "if you multiboot with other linux systems".
