### ISSUE TITLE
Also, add LVM support, LUKS auto-partitioning, BTRFS auto/manual subvolumes and swap files.

### ISSUE THREAD

**Issue by lan-vuhoang** [MatMoul/archfi#115]
Also, add LVM support, LUKS auto-partitioning, BTRFS auto/manual subvolumes and swap files. Because if Manjaro Architect has all of them, then why not this?

**Comment by MatMoul** [comment]
It's very difficult to provide all part shemes...
Long time ago, I've tried to do a part wizard :
https://github.com/MatMoul/archfi/tree/partwizard
Last commit 2015
With my free time, I can't work on this now...

**Comment by lan-vuhoang** [comment]
But there's still time.

**Comment by gfelipe099** [comment]
Man, don't force him too much. Let him work on the script when he is up to. I am sure we all prefer quality instead of quantity.

**Comment by lan-vuhoang** [comment]
An example for creating btrfs subvolumes for /, /home, /var, /opt, /tmp, /srv, /.snapshots and /swap for a swap file on /dev/sda1 from ermannoferrari's tutorial:

`mkfs.btrfs /dev/sda1
mount /dev/sda1 /mnt
btrfs su cr /mnt/@root
btrfs su cr /mnt/@home
btrfs su cr /mnt/@srv
btrfs su cr /mnt/@opt
btrfs su cr /mnt/@var
btrfs su cr /mnt/@tmp
btrfs su cr /mnt/@swap
btrfs su cr /mnt/@.snapshots`

**Comment by lan-vuhoang** [comment]
Mounting these subvolumes: (noatime = no access time; compress = compression, could be lzo, zstd or zlib, requires the according package; subvol = mount a subvolume) (again assuming that the partition is on /dev/sda1)

`mount -o noatime,space_cache,compress=lzo,subvol=@root /dev/sda1 /mnt`
`mkdir /mnt/{boot,home,var,tmp,opt,srv,swap,.snapshots}`
`mount -o noatime,space_cache,compress=lzo,subvol=@home /dev/sda1 /mnt/home`
`mount -o noatime,space_cache,compress=lzo,subvol=@tmp /dev/sda1 /mnt/tmp`
`mount -o noatime,space_cache,compress=lzo,subvol=@opt /dev/sda1 /mnt/opt`
`mount -o noatime,space_cache,compress=lzo,subvol=@srv /dev/sda1 /mnt/srv`
`mount -o noatime,space_cache,,compress=lzo,subvol=@snapshots /dev/sda1 /mnt/.snapshots`

/var and /swap needs specific options: (nodatacow = no data copy-on-write)

`mount -o nodatacow,subvol=@var /dev/sda1 /mnt/var`
`mount -o nodatacow,subvol=@swap /dev/sda1 /mnt/swap`

Mount the EFI partition (assume that it's on /dev/sda2):

`mount /dev/sda2 /mnt/boot`

btrfs-progs is required for btrfs support.
Add btrfs to the `MODULES="..."` section in /etc/mkinitcpio.conf, then regenerate initcpio:

`mkinitcpio -p linux` 

Replace linux with linux-lts or any other kernels that are chosen.

grub-btrfs is also required for btrfs snapshots and grub-mkconfig on btrfs.

**Comment by mirh** [comment]
Even if there is not a dandy fs customized menu with checkboxes, it would still be better than nothing to just add a "do you want to to specify mount options" question.

**Comment by MatMoul** [comment]
Closing old issue...
