### ISSUE TITLE
The mirror country selection should be replaced with a section for using Reflector to rank mirrors.

### ISSUE THREAD

**Issue by lan-vuhoang** [MatMoul/archfi#117]
The mirror country selection should be replaced with a section for using Reflector to rank mirrors. Because just choosing mirrors depending on country doesn't take the mirror's speed into account, and in Arch, mirror speed is a very important factor.

**Comment by MatMoul** [comment]
Until now, reflector was on aur but since 2020-03-21 it is in the commuinity repo.
Need investigation

**Comment by nguyenkhanh2474** [comment]
So just install it from the repo.
This is the creator's other account, by the way.

**Comment by MatMoul** [comment]
Closing old issue...
