### ISSUE TITLE
It should have descriptions for auto partitioning like Manjaro Architect did.

### ISSUE THREAD

**Issue by lan-vuhoang** [MatMoul/archfi#119]
The grub config should also be generated after installing grub into the hard drive instead of after installing the grub package. The current setup means that the grub-mkconfig command will not find anything on BIOS systems, which means that the system can't boot into the OS.

**Comment by MatMoul** [comment]
I'm not sure of the question.
For the autopart solution, I suggest this interpretation :
AutoPart for Newbie or test VM
cfdidk/cgdisk for a more custum part
CTRL+ALT+F2 for real install and advanced config

**Comment by MatMoul** [comment]
Closing old issue...
