### ISSUE TITLE
Add Aur and Chaotic Repo 

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [MatMoul/archfi#120]
could you add both the Aur and chaotic Aur as an option to install ? thanks, both help alot

**Comment by MatMoul** [comment]
No, archfi provide only a base install.
For aur, archdi, archdi-pkg help you to install an aurhelper...
And for external repo, it's definitively no...

**Comment by ReaperOfSouls1909** [comment]
That’s really bad choice on your end oh well not everyone wants a faster arch I guess
