### ISSUE TITLE
wget & wifi-menu don't work in the latest Arch ISO & Reflector?

### ISSUE THREAD

**Issue by nigelwarning** [MatMoul/archfi#125]
So,

In the latest Arch ISO Current Release: 2020.07.01 wget is gone and wifi-menu too. Would be handy if updated in the read-me for new users.
I use curl -L archfi.sf.net/archfi > archfi instead
and then I did sh archfi.

iwctl instead of wifi-menu.

I did 3 installs yesterday with the Archfi script, just because I was experimenting.  The one time when I pressed 'Choose mirrors based on country' it automatically run Reflector and the other 2 times when I pressed on it I had to choose my country.

Thanks for the work anyway! Love the script.

**Comment by MatMoul** [comment]
Sorry for the invalid tag...

Too many request in one issue...

On the project, now curl is the default...
For wifi, it isn't...

It seem to be a good idea to make a wiki that replace the README of the project
