### ISSUE TITLE
Install and test throwing Syntax error

### ISSUE THREAD

**Issue by afelipeor** [MatMoul/archfi#126]
Both the install and testing of this script are throwing `archfi: 29: archfi: Syntax error: "(" unexpected (expecting "}")`

**Comment by hristo-mavrodiev** [comment]
Just verify the checksum of the Arch iso and use "dd" command to copy the installation disk to your flashdrive.
Find the USB name with 'lsblk' command -> /dev/sdb and copy the files.
```
sudo dd if=name-of-iso.iso of=/dev/sdb status="progress"
```
I was using unetbooting and external hdd, then usb created with dd command and worked fine.

**Comment by MatMoul** [comment]
Not sure what the issue but try to download the scipt from a defferent location...
curl -L archfi.sf.net/archfi > archfi
curl -L matmoul.github.io/archi > archfi
