### ISSUE TITLE
Script is not available from given URL

### ISSUE THREAD

**Issue by gramms** [MatMoul/archfi#128]
The archfi script seems to have changed it's URL.
When I try to download the script with curl (wget doesn't work anymore), instead of the actual script I get this:

```
root@archiso ~ # cat archfi
<!DOCTYPE HTML PUBLIC "-//IETF/DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://archfi.sourceforge.net/archfi/">here</a>.</p>
</body></html>
```

So maybe the 2 lines of code, Arch Linux can be installed with, should be updated accordingly.

**Comment by AugustasV** [comment]
`wget archfi.sf.net/archfi` works just fine

**Comment by gramms** [comment]
wget has been removed in the latest iso file (archlinux-2020.07.01-x86_64.iso), so it works on older Images but unfortunately not on this one. If wget does not come back, this should be taken care about.

**Comment by MatMoul** [comment]
wget is now missing in the arch media, use curl
#130
