### ISSUE TITLE
Select mirrors by country - does not work!

### ISSUE THREAD

**Issue by stenioas** [MatMoul/archfi#132]
The new mirrorlist file in the new archiso is different, when selecting the option nothing happens.

**Comment by lan-vuhoang** [comment]
The default mirrorlist is now generated with Reflector. By the way, this is another reason to use Reflector instead. Check out my issue about that: #117

**Comment by MatMoul** [comment]
Sorry, this isn't my code but I'll try to update it

**Comment by zendzo** [comment]
i have the same issue here just now, and i continue by not choose this option.

**Comment by MatMoul** [comment]
Sorry this code seem unusable with new pacman mirror file.
Feature need to be updates or deleted

**Comment by MatMoul** [comment]
I've disabled the feature in the last release
