### ISSUE TITLE
Created Boot partition instead of efi in UEFI boot

### ISSUE THREAD

**Issue by DestroyerXyz** [MatMoul/archfi#135]

**Comment by DestroyerXyz** [comment]
I mean even though I chose UEFI boot it did not create an EFI partition in
/boot

**Comment by mirh** [comment]
The efi partition should be /boot.

**Comment by AtifChy** [comment]
efi partition doesn't necessary needs to be /boot/efi

**Comment by AtifChy** [comment]
@DestroyerXyz  check this page on arch wiki https://wiki.archlinux.org/index.php/Installation_guide#Example_layouts

**Comment by mirh** [comment]
EFI definitively requires a boot partition. 
And if you are going to have it, I don't see wherever else you'd be supposed to mount it. 
(/boot/efi is the old mount point btw afaik)

**Comment by AtifChy** [comment]
/boot can be used as EFI partition. /EFI doesn't require a separate partition on arch at least.

**Comment by MatMoul** [comment]
Thanks for all...
Archfi try to offert a very versatile solution but if you want a very custom solution you need to make your parts and mount it with CTRL+F2...
All is possible...
