### ISSUE TITLE
Make the Disk Partitions menu more noob-proof

### ISSUE THREAD

**Issue by mirh** [MatMoul/archfi#137]
For example, if you use cgdisk after you auto partitioned with dos, it will corrupt the rest of the install (grub will complain embedding isn't supported)

You could have a sub menu like
```
mbr > autopartition or use cfdisk
gpt > autopartition or use cgdisk 
```
or you could just have a divisor in the same screen, like
```
MBR
autopartition
cfdisk
------
GPT
autopartition
cgdisk
```

Separately, I think you could also make a bit more clear that this whole menu is just about "the partition table", with everything else (formatting, mount options and whatnot) being handled in the following menu.

**Comment by MatMoul** [comment]
Hi,
cfdisk support GPT, this shemes isn't possible...
autopart is autopart and cfdisk or cgdisk is advanced (perhaps an advanced text for information...)

**Comment by mirh** [comment]
>  cfdisk support GPT, this shemes isn't possible...

Oh, blast, you are right. 
Then.. also show cfdisk in the GPT sub-menu?

> (perhaps an advanced text for information...)

I would guess, either way, people should be informed about the purpose of that menu to begin with as I was saying.

**Comment by MatMoul** [comment]
Closing old issue...
