### ISSUE TITLE
Can't set blank password for root

### ISSUE THREAD

**Issue by mirh** [MatMoul/archfi#139]
In fact (due to 1c9095692b78b72990d399c5639d9400a42dcca3?) you don't even realize nothing happens when you just press ENTER. 
You'll just figure you can't access root at all once you boot in the actual system.

**Comment by MatMoul** [comment]
root with no password isn't a solution...
the check is here to prevent a bad confirmation of the password.

**Comment by mirh** [comment]
I see. Still, it would be super useful.

**Comment by MatMoul** [comment]
After some test, passwd doesn't accept blank password...
My commit is only to check if the command is accepted (a password and a good confirmaiton).

**Comment by mirh** [comment]
So.. Can't you find a way to use empty passwords?
At the moment, this doesn't even work with normal users.

**Comment by MatMoul** [comment]
I never do that!
