### ISSUE TITLE
Archdi is stuck in "Downloading packages..."

### ISSUE THREAD

**Issue by RealSimba** [MatMoul/archfi#140]
Hello
I began to install Arch Linux using 'archfi', but when reached the 'archdi' script is stopped in Downloading packages stage. I used Git Hub to download. I checked my internet connection and it is working.

What could be wrong and what to do?

**Comment by GavinHalo100** [comment]
same

**Comment by GavinHalo100** [comment]
this should be fixed

**Comment by GavinHalo100** [comment]
Someone pls fix im tryna make a arch Linux install

**Comment by MatMoul** [comment]
https://github.com/MatMoul/archdi/issues/14
