### ISSUE TITLE
Can't select options in VM

### ISSUE THREAD

**Issue by ghost** [MatMoul/archfi#142]
Whenever i try to select an option with Y or deselect it with N in VirtualBox it doesn't work, every other key works as intended (Tab, Enter, etc.) but not Y and N. Is there any way to fix this?

**Comment by MatMoul** [comment]
Not sur what you meen by select an option but if this is to check or uncheck item in menu, use SPACE.

**Comment by MatMoul** [comment]
Closing old issue...
