### ISSUE TITLE
Btrfs Subvolumes

### ISSUE THREAD

**Issue by ghost** [MatMoul/archfi#143]
Hey, nice script.

Just wondering if you choose btrfs will the subvolumes be created? If so, which will be?

Thanks

**Comment by AtifChy** [comment]
no subvolumes will be created.

**Comment by MatMoul** [comment]
@talbergor Yes a subvolume is created.
The root subvolume is named root and it is set as default subvolume

**Comment by neuro-prog** [comment]
> @talbergor Yes a subvolume is created.
> The root subvolume is named root and it is set as default subvolume
Great script! Thank you.
With regards to this btrfs matter this is what I have in my fstab
`UUID=6f52edd6-43b4-47cd-bf33-8c18493b474a	/         	btrfs     	rw,noatime,ssd,space_cache,subvolid=5,subvol=/	0 0`
Is that what it's intended to be?

**Comment by brownsnow** [comment]
You dont want it like that for timeshift to work correctly. Everything should be in subvolums.

**Comment by MatMoul** [comment]
Closing old issue...
