### ISSUE TITLE
Not Working Well, Not Recomended

### ISSUE THREAD

**Issue by mad-cs** [MatMoul/archfi#151]
Has so much errors. Not recomended. It's more easier to install Arch with hand.

**Comment by nigelwarning** [comment]
Lol

**Comment by mad-cs** [comment]
Really not working well its more easier to install arch with hand. this bloats the arch too

**Comment by nigelwarning** [comment]
I have done both Arch wiki and Archfi and Archfi works great for me. I use Archfi my latest Arch Installs all the time.

**Comment by mad-cs** [comment]
Not recommended for begginers
