### ISSUE TITLE
Defaulting to Bios installation

### ISSUE THREAD

**Issue by sfb0519** [MatMoul/archfi#154]
In this most recent version while setting up GPT it automatically defaufts to bios mode. Had to manually create partitions for efi installation.  This is being done on a Asus Tuff laptop legacy bios isn't a option.

**Comment by MatMoul** [comment]
Not sure how you have started your computer,
but is you start it in bios mode, you don't have gpt features by default
Solution :
1 : Start your computer in EFI mode
2 : Start archfi with the -efi1 or -efi2 args

**Comment by MatMoul** [comment]
Closing old issue...
