### ISSUE TITLE
Script does not create/update /etc/hosts file

### ISSUE THREAD

**Issue by i28v** [MatMoul/archfi#157]
This file is required for networking and serious problems can occur if this file is missing, you should make the install script create the file and fill it with this information:

```
127.0.0.1	localhost
::1		localhost
127.0.1.1	myhostname.localdomain	myhostname
```

**Comment by MatMoul** [comment]
Can you explain the serious problem?

The arch wiki say :

> The myhostname Name Service Switch (NSS) module of systemd provides local hostname resolution without having to edit /etc/hosts

https://wiki.archlinux.org/index.php/Network_configuration#Local_hostname_resolution

**Comment by i28v** [comment]
The link you posted is misleading, if you didn't need to update /etc/hosts then the arch wiki wouldn't tell you to so in the installation guide.

**Comment by MatMoul** [comment]
This isn't the answer I expected ...
What are the problems if you don't have the /etc/hosts file and it's managed by NSS enabled by default?
Try to provide some technicals infos (an other page of the Arch Wiki or a thread in the Arch Linux forum).

**Comment by MatMoul** [comment]
Closing old issue...
