### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by geeflaxx** [MatMoul/archfi#158]
I love your work!
you takes me a lot of time!

what do you think about a split of  encrypt home and encrypt root with the same password?
so if someone want to split his root and home but encrypt with the same password (for login you only need ones), but you have to seperate partitions what are encrypted.

here are a sample of the code:

modprobe dm-crypt
#cryptsetup -c aes-xts-plain -y -s 512 luksFormat /dev/$ROOT
#cryptsetup -c aes-xts-plain -y -s 512 luksFormat /dev/sda2
#cryptsetup luksOpen /dev/$ROOT lvm
cryptsetup luksOpen /dev/sda2 lvm
pvcreate /dev/mapper/lvm
vgcreate vgarch /dev/mapper/lvm
lvcreate -n lvroot -L 20G vgarch
lvcreate -n lvhome -l 100%FREE vgarch

greetings bro

**Comment by MatMoul** [comment]
Thanks but it's not a good idea to try to provide more autoparts solutions.
My first reply that is always actual : https://github.com/MatMoul/archfi/issues/55#issuecomment-500169455
And my second reply : https://github.com/MatMoul/archfi/issues/43#issuecomment-573270358

**Comment by MatMoul** [comment]
Closing old issue...
