### ISSUE TITLE
Syntax error near unexpected token 'newline'

### ISSUE THREAD

**Issue by winnaingsoe** [MatMoul/archfi#159]
After Download, run "sh archfi"
archfi: line 1: syntax error near unexpected token 'newline'
archfi: line 1: '<!DOCTYPE HRML PUBLIC "-//IETF//DTD HTML 2.0//EN>'

**Comment by MatMoul** [comment]
Are your sure that you doenload is ok?
what return `cat archfi` ?

**Comment by JamesUNT** [comment]
That's what appear on mine when I tried to execute `sh archfi`:

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML2.0/EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://archfi.sourceforge.net/archfi">here</a></p>
</body></html>

**Comment by Diamond285970** [comment]
Try `curl -L archfi.sf.net/archfi`.

**Comment by JamesUNT** [comment]
Now it's working, but I tried this command before and now it's working, something has changed ?
