### ISSUE TITLE
[Feature Request] A Archfi iso that automatically runs Archfi

### ISSUE THREAD

**Issue by SlushThorsten** [MatMoul/archfi#166]
I hate the need to use the Arch Installer and then install Archfi there,cause I always forget the full name to install Archfi.
So I would like to be able to install a Archfi iso that automatically boots Archfi.
For that you would need to select to update the Arch installer inside Archfi.

**Comment by MatMoul** [comment]
I don't want to maintain an iso.
You are free to make it if you want...
Perhaps with an /usr/bin/archfi that download the latest archfi

**Comment by Toadfield** [comment]
How exactly can I make my own?
I have no idea about how to do that.
But if that's easily possible,then you could make a extra release that gives a standalone archfi installer that automatically has the newest arch and everytime there is a new arch release,then there will automatically be a new release,then you won't have to maintain that.

**Comment by kuohuanhuan** [comment]
> How exactly can I make my own?
> 
> I have no idea about how to do that.
> 
> But if that's easily possible,then you could make a extra release that gives a standalone archfi installer that automatically has the newest arch and everytime there is a new arch release,then there will automatically be a new release,then you won't have to maintain that.

Easily, reference bootra1n!

**Comment by DestroyerXyz** [comment]
I don't think this is worth the hassle

And the download link is very easy to remember

**Comment by lucasburlingham** [comment]
One can build your own ISO with [mkarchiso](https://github.com/archlinux/archiso).

Place the line `curl -LO archfi.sf.net/archfi | sh` in `airootfs/root/.bashrc` to automatically run it when you start the ISO image.

**Comment by MatMoul** [comment]
Closing old issue...
