### ISSUE TITLE
Grub-install error

### ISSUE THREAD

**Issue by xeeth** [MatMoul/archfi#169]
Might have done something wrong, but I looked over every possible thing and I don't get why this happens. Disk is partitioned correctly
![IMG_20210215_234954](https://user-images.githubusercontent.com/43382055/107997446-6d7f7780-6feb-11eb-9428-22d015028133.jpg)

**Comment by Hansel-Dsilva** [comment]
Have you created a >1 MB boot partition for installing the bootloader? It need not not have any filesystem type or flags, just a separate partition for grub-install to detect.

**Comment by kuohuanhuan** [comment]
Just reinstall and create a 512MB space for /boot @xeeth

**Comment by MatMoul** [comment]
Closing old issue...
