### ISSUE TITLE
[Question] KDE applications

### ISSUE THREAD

**Issue by yesvery-xinnux** [MatMoul/archfi#172]
I want to install plasma5 as my Desktop Environment but idk what "KDE Applications" are and if I need them.

**Comment by TheSilencedOne** [comment]
"KDE applications" are the apps that come preinstalled with the KDE plasma desktop 
(You probably want to go through and choose which ones you want or else you will end up with alot of bloat)

**Comment by MatMoul** [comment]
Closing old issue...
