### ISSUE TITLE
Cant add new user? 

### ISSUE THREAD

**Issue by DeathsDoor56** [MatMoul/archfi#186]
I am having an issue with create a user. It says 

User SoandSo created. 

Choose a password for SoandSo :

passwd: User ‘SoandSo does not exist 
Press any key to continue. 

Is there any solution to this?

**Comment by MrAmericanMike** [comment]
I'm not 100% sure. But the user should be all lowercase. Try with a lowercase name and see how it goes.

https://unix.stackexchange.com/questions/235049/is-the-username-in-unix-case-sensitive

Apparently they can have uppercase, but cause issues. Something to look into by people that know more about this.

**Comment by DeathsDoor56** [comment]
Thank you so much!

**Comment by DeathsDoor56** [comment]
> I'm not 100% sure. But the user should be all lowercase. Try with a lowercase name and see how it goes.
> 
> 
> 
> https://unix.stackexchange.com/questions/235049/is-the-username-in-unix-case-sensitive
> 
> 
> 
> Apparently they can have uppercase, but cause issues. Something to look into by people that know more about this.
> 
> 

This was the solution I was typing my user with a capital letter after I did lowercase I can add a user now

**Comment by DeathsDoor56** [comment]
> I'm not 100% sure. But the user should be all lowercase. Try with a lowercase name and see how it goes.
> 
> 
> 
> https://unix.stackexchange.com/questions/235049/is-the-username-in-unix-case-sensitive
> 
> 
> 
> Apparently they can have uppercase, but cause issues. Something to look into by people that know more about this.
> 
> 

Do you have a solution I just effed up big time so I took out my usb after I got it set up and it brought me to "reboot or select proper boot device." Screen and the worst possible thing has happened. My keyboard doesn't work. I tried several USB ports none work. It's a led keyboard it won't light up or do anything.
