### ISSUE TITLE
I think I bricked my pc/bios??

### ISSUE THREAD

**Issue by TheCh0osen1Coder** [MatMoul/archfi#191]
[Question] So I am a complete begineer to arch. I tried to install arch linux for the first time on a secondary pc with the use of Archfi. When I tried to format the partitions (idk if I spelled that right) I selected /dev/sda1 as the linux boot. In the screen before that the partition was called BIOS BOOT. When i clicked format, the pc froze and then the screen shutdown. I tried rebooting but the only thing that was happening was the fan spinning. Nothing else. There was no video signal, no nothing. There was power to the pc and the monitor was indeed plugged into the pc. Idk what to do with the pc now because it doesnt work at all... Can anyone please help me?

(Btw I tried to ask this on r/archlinux but a mod locked my post telling me to consult this project because archfi != arch linux)

**Comment by gghhkm** [comment]
What brand is you PC. If it's a Custom built pc then whats the motherboard brand?

**Comment by TheCh0osen1Coder** [comment]
The pc motherboard is an asrock one but idk the model. Its not custom built though

**Comment by MatMoul** [comment]
Closing old issue...
