### ISSUE TITLE
Syntax error near expected token `<‘

### ISSUE THREAD

**Issue by FlyDownGames** [MatMoul/archfi#196]
After I install archifi using `curl -L archifi.sf.net/archifi > archifi` and then use the command `sh archifi`, this appears:
```
archifi: line 1: syntax error near unexpected token `<’
archifi: line 1: `<html><head><title>Encountered a 404 error</title>
```

And If I install archifi using `curl -L matmoul.github.io/archifi > archifi` and then use the command `sh archifi`, this appears:
```
archifi: line 1: syntax error near expected token `newline’
archifi: line 1: `<!DOCTYPE html>’
```

**Comment by FlyDownGames** [comment]
Ok im tired sorry for my stupidity 😂

**Comment by Prograb** [comment]
??? tell us the fix
