### ISSUE TITLE
[Feature Request] themes for GRUB/rEFInd

### ISSUE THREAD

**Issue by Araraura** [MatMoul/archfi#197]
Hello, I wanted to ask if it would be possible to add a feature to download and install a theme for grub/refind/other bootloaders when installing them using archfi.

**Comment by pcoopergit** [comment]
You can mod the script with suitable labels, options & links. Then get a pull req here.

**Comment by Araraura** [comment]
> You can mod the script with suitable labels, options & links. Then get a pull req here.

I don't know how to do that, hence the feature request label.

**Comment by MatMoul** [comment]
Closing old issue...
