### ISSUE TITLE
[Feature Request] An option entry to access terminal

### ISSUE THREAD

**Issue by its-ishan** [MatMoul/archfi#203]
Pardon me if this has been requested already (or if it cant be done) but is it possible to **add an option to access terminal** once the script has been started. What I mean is currently **once the script starts we only have to go through the entire process and can leave by either rebooting or unmounting which leaves us back to chroot environment.** 
Any further changes (if we want) can be done only after remounting from the chroot environment.

So I would like to  **request a feature to access back the command line both from archfi and archdi** so that any custom enhancements (say modification of configs, extra packages) can be installed in the middle of install.

One already implemented scenario is editing of fstab,sudoers and grub config files. This is great but can be enhanced if we can access command line directly, not just editor.

This feature (or similar) can resolve lots of issues of customization that people have raised (I was reading previous opened issues). Also this is one of a kind, no other installer has this kind of  capability (not that i know of) (also i am excluding bare metal arch install).

**Comment by DreitTheDragon** [comment]
I used CTRL+ALT+F2 (up to F6) for this last time to set up additional hard drive options.

**Comment by MatMoul** [comment]
Closing old issue...
