### ISSUE TITLE
error when installing

### ISSUE THREAD

**Issue by ThatOneDev-Code** [MatMoul/archfi#204]
Whenever I install arch manually or with a install script, I get thrown into the grub rescue screen with a unsupported file system error.
Can anyone help me? Ive really wanted to switch to arch for a while but didn't want to use any of the other distros.
Thanks!

**Comment by ArijitKHaldar** [comment]
Would it be possible for you to make a list of all the commands that you used to install Arch right from the beginning? We can then eliminate some issues specific to your system, if manually installing Arch works for once...then you can try any script you want.

Or, you may also send your requirements - like, the file system type you are trying to use, UEFI/BIOS, number of partitions you need, etc., then I'll try to make a simple script or a notes for you to follow, in case something is going wrong.

**Comment by ThatOneDev-Code** [comment]
im using a uefi  file system, i just the root, swap, efi and home partitions. have no idea what file sys to use.

when i run the script i just go through it normally and does what it recommends.
ill try and replicate it in a vm to give more info.

**Comment by ArijitKHaldar** [comment]
@ThatOneDev-Code Great...I am making a quick script for you (just the vanilla way of installing Arch). Would you please let me know your total disk size? Then I'll partition with sensible limits.

Then we will see how things go from there...

**Comment by ThatOneDev-Code** [comment]
@ArijitKHaldar its around 400gigs

**Comment by ArijitKHaldar** [comment]
@ThatOneDev-Code Please check this repo. Go through the README and edit the script as suited for you. I have placed comments wherever you might need to change something. Let me know if you face any issues. Hope this will help you to get on Arch.
- [ArchLinuxInstall](https://github.com/ArijitKHaldar/ArchLinuxInstall)

**Comment by MatMoul** [comment]
Closing old issue...
