### ISSUE TITLE
Kernel install dialog: linux-grsec need to be replaced.

### ISSUE THREAD

**Issue by FredBezies** [MatMoul/archfi#21]
It is now replaced in Archlinux by linux-hardened : https://wiki.archlinux.org/index.php/Security#Kernel_hardening and https://github.com/copperhead/linux-hardened

**Comment by MatMoul** [comment]
Thanks for the report I'll correct it soon...

For info : linux-grsec is part of archdi-pkg : https://github.com/MatMoul/archdi-pkg

**Comment by MatMoul** [comment]
Package updated

**Comment by FredBezies** [comment]
Thanks.
