### ISSUE TITLE
archdi dont execute

### ISSUE THREAD

**Issue by icantstopp** [MatMoul/archfi#215]
when it comes time to select archdi, it just doesn't run anymore, you click to install and start, and it doesn't start, it just goes back to the install screen

**Comment by MatMoul** [comment]
It looks like whiptail is broken after popt update.

At this time, the only way is to downgrade popt.

I'm trying to switch to dialog but I need some time.
I hope that I can publish a new release soon.

**Comment by MatMoul** [comment]
I've published two new branch with dialog (One with dialog and the second with a themed dialog).
For me, the second is better for my eyes.

Need testers et feedbacks.
curl -LO archfi.sf.net/archfi
sh archfi -t matmoul dialog
sh archfi -t matmoul dialogcustom

**Comment by icantstopp** [comment]
i'll test new, and i return with feedbacks

**Comment by icantstopp** [comment]
what is happening now is the following, after clicking to install and run, it appears the archdi screen, updates, install etc, but as soon as you select some it returns to the installation part

**Comment by MatMoul** [comment]
If I've updated archfi in 3 hours, but this is because I work from two night with the same break of archdi.
The dialog branch of archdi is ready but not archdi-pkg (need more time for this)...

Thanks for first feedback

**Comment by icantstopp** [comment]
i understand, good job

**Comment by MatMoul** [comment]
I just pushed the first good commit for archdi-pkg with dialog but you can't use it from archfi (This is dev versions).

For testing :
Install arch linux with the new archfi script.
At the end choose to install archdi.
Finish the archfi install script and reboot.

After logged in as root, run :
archdi -t matmoul dialog
archdi -t matmoul dialogcustom

**Comment by MatMoul** [comment]
New release of archfi, archdi, archdi-pkg solve all issues with dialog as replacement to whiptail.

**Comment by icantstopp** [comment]
the script dont run now

Em qui., 10 de nov. de 2022 às 17:41, MatMoul ***@***.***>
escreveu:

**Comment by MatMoul** [comment]
I've updated archfi with the a call of `pacman-key -u` that prevent installing dependencies at the first launch.

**Comment by icantstopp** [comment]
its working, thanks soo much

Em sex., 11 de nov. de 2022 às 10:18, MatMoul ***@***.***>
escreveu:
