### ISSUE TITLE
[wish] install base-devel with base

### ISSUE THREAD

**Issue by FredBezies** [MatMoul/archfi#22]
It could be great to install from the beginning base-devel with base in order to get some building tools even if you don't install any aur-wrapper like yaourt after this first step.

Also, as a feedback, I can tell Mate installation worked great :)

**Comment by MatMoul** [comment]
Thank for your return.
I'm not sure that archfi is the good place for base-devel.
But I can add it on archdi-pkg

**Comment by MatMoul** [comment]
Added and checked by default in Install, Console, Generic

**Comment by FredBezies** [comment]
Thanks.
