### ISSUE TITLE
Flatpak commands need to be run as sudo

### ISSUE THREAD

**Issue by telometto** [MatMoul/archfi#220]
I don't know if there's some step that the script does or does _not_ do but, whenever I use this script to do a fresh Arch install, installing the `flatpak` package and executing `flatpak` commands require elevated privileges (which, sort of defeats the whole purpose of the technology).
I'm asking here because using the default `archinstall` script does not encounter the same issues. Is this intended functionality?

Amazing script, nonetheless! Without a doubt the best one out there 😊

**Comment by MatMoul** [comment]
After some research I see that archinstall adds your user to the wheel group.
I think that's the reason.

**Comment by telometto** [comment]
I see. I'll just manually add the users, then. Thanks for clearing that up 😊
