### ISSUE TITLE
When using auto partitioning, you don't really know which partition is which

### ISSUE THREAD

**Issue by telmotrooper** [MatMoul/archfi#23]
I'd like to start by saying I really appreciate your work here.

The only problem I found so far is that when you do auto partitioning, the script creates each partition but it doesn't tell you which is which. So in the next step when you have to pick where the mountpoints will be, you don't know the size of the partitions created to know which you're gonna use for what, unless you go look at your disk information and then reopen the script.

**Comment by MatMoul** [comment]
Thanks for return,
You're right, this is the autopart but you can always make your own partition with cfdisk or cgdisk or CTRL+F2 and use your own part tools for this.

**Comment by MatMoul** [comment]
I missing time but in the futur, i'll try to provide a wizard that you can create desired partitions and set desired size of each partition.

**Comment by telmotrooper** [comment]
I appreciate your swift answer.

**Comment by mrcasquinhas** [comment]
It says 'select boot device' and auto-selects sda1. Then says 'select swap device' and selects sda3. Then it says 'select root device' and auto-selects sd4. Then 'home device' and selects none.
So it's not bad at all. You do have to know that sda1 has to be fat32 for EFI and you choose the others.
So, it can be better? Yes, but if you you're doing a 'hand' install, I think you have an idea of what you're doing.
