### ISSUE TITLE
SSD Support

### ISSUE THREAD

**Issue by emporeso2** [MatMoul/archfi#31]
Hi i'am trying your script , it worked very good , would be nice if the support of ssd drives could be include ?

**Comment by MatMoul** [comment]
Thanks for the return.

Not sure for the support of ssd, I only retained the activation of the service fstrim.timer.
For that, I'll add an option...
Do you make any other changes?

**Comment by emporeso2** [comment]
Thanks that what i was thiking about the trim option.

**Comment by MatMoul** [comment]
I reopen the issue so as not to forget it ...

**Comment by MatMoul** [comment]
Removed the enhancement label because I'm not sure it's good to add this option on archfi...
Perhaps in archdi-pkg

**Comment by MatMoul** [comment]
Now you can enable or not the service in archdi config systemd services...
