### ISSUE TITLE
grub-mkconfig fails No such file or directory

### ISSUE THREAD

**Issue by RamonRobben** [MatMoul/archfi#35]
On the Arch Install Menu:
![image](https://user-images.githubusercontent.com/12982618/49638933-f234db00-fa09-11e8-9207-c8b5e4b87c6c.png)

After selecting that option it installs the packages but after pressing enter it then tries to create the grub and it fails like this:
![image](https://user-images.githubusercontent.com/12982618/49638991-185a7b00-fa0a-11e8-9961-176263e6bdc9.png)

Then once you install the bootloader you have to go back to Install Grub and select it again.
When you do it the second time it re-installs the packages and it won't fail at grub-mkconfig -o /boot/grub/grub.cfg

I have looked over this multiple times when installing I was wondering if those two options are in the wrong order or if its just something intentionally? This happened on two machines (1 VM and 1 Laptop)

**Comment by MatMoul** [comment]
I've constated too this problem from two or three week...
I'll update the code but I'm missing time... This is the end of the year and I need to priorities my job...
Temporary, you can launch a second time "Install grub" after "Install bootloader" or follow archdi that run grub-mkconfig when you install kernel or driver packages

**Comment by RamonRobben** [comment]
> 
> 
> I've constated too this problem from two or three week...
> I'll update the code but I'm missing time... This is the end of the year and I need to priorities my job...
> Temporary, you can launch a second time "Install grub" after "Install bootloader" or follow archdi that run grub-mkconfig when you install kernel or driver packages

Sure thing take your time. It's not a major problem.

**Comment by MatMoul** [comment]
I've updated the code to create the grub dir before grub-mkconfig
