### ISSUE TITLE
Support for HiDPI...

### ISSUE THREAD

**Issue by workdowg** [MatMoul/archfi#37]
Kind of hard to use the menus with a magnifying glass... Even though (with a magnifying glass) I download a font and change it with setfont then enter Archfi  after I get through the first couple menus it goes back to tiny.. I guess I could just ssh in to it but if it could be set within Archfi that would help. Fantastic job on this and thank any which way...

**Comment by MatMoul** [comment]
Archfi is a console app...
I'm not sure to understand your request.
Please, provide a screenshot or an anim...

**Comment by workdowg** [comment]
Sorry for the confusion and sorry for the poor quality pics coming, I don't have time to learn to change settings on my camera to get better pics of screens...... Once the Arch install media (archiso) loads it has a very tiny font on 4K monitors (see  https://photos.app.goo.gl/pCxH7XKrDURRcfyZ7 ). What I have been doing is change the the console font to something large enough to see (install terminus-font and then "setfont ter-132n") without a magnifying glass (see https://photos.app.goo.gl/BXggv3d4SZ6JTzD86 )... But when I launch your script it is fine (see https://photos.app.goo.gl/X585GDomwYkLSQMv7 ), but after I pick the language it reverts back and everything is way too small too work with (see https://photos.app.goo.gl/KeygB2EnW6KQbNjd8 ).

**Comment by MatMoul** [comment]
Ok the reason is that when you choose a language, the language file contain the font for the language...
On the next version, I will try to provide an argument that skip setting font but it's only possible for some languages.
As exemple Russian use cyrillic chars...

**Comment by workdowg** [comment]
That will help the few of us that this affects... No hurry, ssh into the install does work better anyway. The archiso should be considering have 4k monitors anyway... Thank for your time..

**Comment by MatMoul** [comment]
@workdowg Can you test with these next cmd with arg -sf or --skip-font :
`wget https://raw.githubusercontent.com/MatMoul/archfi/src/archfi`
`sh archfi -sf`

**Comment by workdowg** [comment]
Perfect... Worked without a hitch! Thanks for helping these old eyes. ;)

**Comment by MatMoul** [comment]
New version released with -sf args

**Comment by KarkanAlzwayed** [comment]
Let me see if I understand this correctly. First I'd have to do the "wget archfi.sf.net/archfi" then before I do "sh archfi" I'd do this "wget https://raw.githubusercontent.com/MatMoul/archfi/src/archfi
sh archfi -sf"
Then the font becomes bigger?
Or do I need to use the setfont command then do those two things I've just mentioned?
