### ISSUE TITLE
Systemd-boot option

### ISSUE THREAD

**Issue by spsf64** [MatMoul/archfi#38]
Is it possible to add option for "systemd-boot" too?

Thanks for this great project, it is amazing!

**Comment by MatMoul** [comment]
Hi, currently, I'm working to make a child menu for bootloaders...
When ready, I'll first add syslinux.
For Systemd-boot and rEFInd I need to learn more...
Anyone can contribute for other bootloaders but wait that the bootloader child menu is ready in the src branch.
When it's ready, I'll tag this issue as help wanted

**Comment by MatMoul** [comment]
Removed help wanted becaus I work now on systemd-boot

**Comment by MatMoul** [comment]
systemd-boot releases

**Comment by MatMoul** [comment]
On archfi, you only install the base and you don't have ucode installed...
Currently, I'm study if it's best to add it on archfi or to handle it on archdi-pkg

**Comment by MatMoul** [comment]
I've just tested to add ucode file without installing it and this break the boot
Now I can add the line with comment or manage it with archdi-pkg
It seem best to manage it with archdi-pkg

**Comment by spsf64** [comment]
Ok, I see, maybe the best way..
That is similar to what I did, editing the file manually.

**Comment by MatMoul** [comment]
@spsf64 I've added some feature in archdi-pkg for systemd-boot...
Entries (edit, update ucode, create, delete)
systemd-boot (Update, create or delete the pacman hook)

**Comment by spsf64** [comment]
@MatMoul thanks for all your effort and feedback! 
I try another install next week and let you know how it goes.

**Comment by MatMoul** [comment]
@spsf64 Thanks, I can drink one more beer...
Cheers!
