### ISSUE TITLE
Condres OS

### ISSUE THREAD

**Issue by specialworld83** [MatMoul/archfi#39]
good evening, we have made the fork of your text installer for our operating system. We have disabled the desktop installation because we were only interested in a basic system. Here is the link of the operating system and on github.

[https://github.com/specialworld83/condres-cli-installer](https://github.com/specialworld83/condres-cli-installer)
[https://condresos.codelinsoft.it](https://condresos.codelinsoft.it)

[https://condresos.codelinsoft.it/index.php/support/wiki/installation-with-condres-cli-installer](https://condresos.codelinsoft.it/index.php/support/wiki/installation-with-condres-cli-installer)

**Comment by MatMoul** [comment]
Thanks for the info, I'll look at your project...
I'm always happy when my code is used...

**Comment by specialworld83** [comment]
Good afternoon,
I was wondering if you would like to join our team and make sure to completely adapt your script to our distribution. Always if you like, of course.

**Comment by MatMoul** [comment]
@specialworld83 Thanks for the proposal but I'm afraid that I don't have enough free time ...
