### ISSUE TITLE
Add a note or message when installing "/home" to /

### ISSUE THREAD

**Issue by spsf64** [MatMoul/archfi#40]
![home-part](https://user-images.githubusercontent.com/1877391/50566674-90734280-0d23-11e9-875d-09f865260e30.jpeg)

In picture above, you could add a message/note to select "none" when the user in using a single root partition, just to clarify it?

**Comment by MatMoul** [comment]
Thanks for your return but in console the size is limited...
If you use autopart just press enter...

**Comment by MatMoul** [comment]
@spsf64 Ok I tag to possible enhancement but it isn't a priority

**Comment by mirh** [comment]
I think you should rework a bit all this part, not just for /home. 
Like, "swap=none" seems to imply quite a different thing to be honest - and only after wondering why in the hell *format* was making me wipe four times the same partition I understood the true meaning. 

I think previously selected partitions should not be available in subsequent choices. 
(also, is there any reason why whole /dev/sd*x* disks are offered?)

**Comment by MatMoul** [comment]
Closing old issue...
