### ISSUE TITLE
Syslinux bootloader error

### ISSUE THREAD

**Issue by diegomontanaduarte** [MatMoul/archfi#41]
I get an error while installing Syslinux bootloader using your installation script

"ERROR: Could not stat device /dev/nvm No such file or directory"

I'm using NVMe disk and it's assigned to a block device "/dev/nvme0n1". Could you please advise?

**Comment by MatMoul** [comment]
I've just tested for the first time NVM controler and it seem that have 2 bugs...
The first is when you autopart, the auto selection of partition doesn't work.
You need to select it manualy...
And the second, I suspect this is your problem...
You need to add nvme module in mkinitcpio.conf...
You can edit it with archfi (it's an optional option) before installing systemd-boot.

I'll try to handle these cases when I would find the time...

**Comment by MatMoul** [comment]
Sorry, I've readed systemd-boot but it's syslinux...
Just tested it and I encouter the same problem...
The mkinicpio.conf need to be edited but for your error I investigate...

**Comment by MatMoul** [comment]
I can't sleep with this bug...
I've just pushed a new version that support now nvme drive

**Comment by diegomontanaduarte** [comment]
Works like a charm! Thanks for your quick support.

I would like to suggest a country based selection on mirrorlist option, like Pacman Mirrorlist Generator tool - https://www.archlinux.org/mirrorlist/
