### ISSUE TITLE
Question: The ability to safely install Arch Linux using cryptsetup and LVM?

### ISSUE THREAD

**Issue by bardimnik** [MatMoul/archfi#42]
Hello! With the help of your script, I met Arch Linux. I really liked Arch Linux. Now I use it everyday on my computer and laptop. Thanks you!
Question: Will the possibility of a secure installation of Arch Linux with the help of cryptsetup and LVM will be implemented?

**Comment by bardimnik** [comment]
Can you make a video about the safe installation of Arch Linux using archfi and archdi? And put this video on your channel? I'll be very grateful.

**Comment by bardimnik** [comment]
I see, thanks! Will the above function be implemented?

**Comment by MatMoul** [comment]
Not for autopart functions but I've some idea to make a partwizard...
But time is missing now...
Wait and see !!!

**Comment by DanitiKain** [comment]
@MatMoul thanks for all your effort. With this feature it will be now so much easier to get arch up and running quickly.

**Comment by TheLinuxNinja** [comment]
I think I'll tackle the option to do Full Disk Encryption using LUKs and LVM.
This is how I usually install laptops, so I have quite a bit of experience with this.

Let me know if this is something you'd be willing to merge and if you have suggestions how to integrate it into the menu system.

**Comment by bardimnik** [comment]
Hello!I agree to help You test these script functions.Thank You for creating such a good archlinux installation script.With its help, I transferred to the use of ArchLinux all my family and friends.I tried installing ArchLinux on an LVM with encryption, but there's a lot of manual work involved and don't quite understand how this should be done CORRECTLY. If this feature will be implemented using a script, it will promote the use of ArchLinux to the masses of people. For my part, I can promise to make a couple of video tutorials on the use of the script and possibly place a few text tutorials in Russian blogs. I'll wait for Your messages. 08.06.2009, 06:32, "Bryan G." <notifications@github.com>:I think I'll tackle the option to do Full Disk Encryption using LUKs and LVM.This is how I usually install laptops, so I have quite a bit of experience with this.Let me know if this is something you'd be willing to merge and if you have suggestions how to integrate it into the menu system.—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.  -- With respect, Mr Baranda.My phone: +7 (960) 020-47-64My e-mail: bardimnik@yandex.ru

**Comment by MatMoul** [comment]
Follow #55

**Comment by ben-utzer** [comment]
> I think I'll tackle the option to do Full Disk Encryption using LUKs and LVM.
> This is how I usually install laptops, so I have quite a bit of experience with this.

I as a user of the script would like to see this, even with the SWAP partition in the LVM inside the LUKS, this is something I always struggled with on a manual installation. No matter if LUKS/LVM or LVM/LUKS or just LUKS, it is hard to setup manually. Having such an option in a installer (script) would be very helpful an increase safety and usability, I think for hibernation to work it is easier too, not sure why this doesn't work with the current archfi, but it might be one reason.

**Comment by drewboardman** [comment]
Any news on this?

**Comment by ben-utzer** [comment]
> I as a user of the script would like to see this, even with the SWAP partition in the LVM inside the LUKS, this is something I always struggled with on a manual installation. No matter if LUKS/LVM or LVM/LUKS or just LUKS, it is hard to setup manually. Having such an option in a installer (script) would be very helpful an increase safety and usability.

A /swapfile solution would be OK too, maybe dphys-swapfile or so (as in Debian) would be working, not sure about hibernation in this case, but hibernation is my goal for the swap creation.
