### ISSUE TITLE
RFE: Create Luks and LVM Partitioning

### ISSUE THREAD

**Issue by DanitiKain** [MatMoul/archfi#43]
Would like the option in the script to create auto partitioning with LUKS and LVM as an option.

**Comment by MatMoul** [comment]
https://github.com/MatMoul/archfi/issues/42#issuecomment-455330961

**Comment by TheLinuxNinja** [comment]
reposting here:

I think I'll tackle the option to do Full Disk Encryption using LUKs and LVM.
This is how I usually install laptops, so I have quite a bit of experience with this.

Let me know if this is something you'd be willing to merge and if you have suggestions how to integrate it into the menu system.

**Comment by MatMoul** [comment]
Perhaps linked to #55

**Comment by TheLinuxNinja** [comment]
I treat LVM on Luks as a separate problem than UEFI, but yes, I can tackle both when I have time.

**Comment by MatMoul** [comment]
I suggest to merge this issue to https://github.com/MatMoul/archfi/issues/55#issuecomment-501458874

**Comment by praetorxyn** [comment]
Seconded. Unless it will let me create LVM / LUKS, archfi is completely useless to me as I simply will not do a Linux install without LVM, and I wouldn't do a Linux install on a laptop without LUKS as well.

LVM / LUKS always seems to be the linchpin where these "installer scripts" fail; either they won't let you do it at all, or they will but won't let you specify names for your volume group(s) / logical volume(s) / etc.

**Comment by MatMoul** [comment]
@praetorxyn It's very difficult to offer all the part sheme avaible in linux...
This is why you can press `CTRL+F2` to make your own part sheme and mount it as you want...
Then you can come back to archfi with `CTRL+F1` and select your partitions...

**Comment by praetorxyn** [comment]
That's what I ended up doing, though in this case I decided to just do LUKS
and try out a custom btrfs subvolune scheme.

**Comment by nicekiwi** [comment]
Maybe I'm mis-understanding the issue, but setting up  LVM + LUKS with archfi works fine for me without doing anything custom.

**Comment by Staubgeborener** [comment]
> 
> 
> Maybe I'm mis-understanding the issue, but setting up LVM + LUKS with archfi works fine for me without doing anything custom.

like - how?

**Comment by MatMoul** [comment]
Closing old issue...
