### ISSUE TITLE
Add instructions to add the installer in the archiso.

### ISSUE THREAD

**Issue by roipoussiere** [MatMoul/archfi#45]
There is [a guide on the Arch wiki](https://wiki.archlinux.org/index.php/Remastering_the_Install_ISO) to remaster the Arch iso.

In this way it's possible to add the arch installer in the iso before mounting the iso on a flash drive.

These instructions, or a link to this page could be added on the readme, which would look like this:

- archfi
    - How to use
        - Method a: create regular iso then download the script from it
        - Method b: create remastered including the script

Having the installation script already in the archiso could be really useful. Among other things, this would allow adding in that installer some functions that configure the internet connection.[1]

It would be very helpful in particular when installing Arch via a wireless connection (some modern laptop does not have Ethernet plug).

---

[1]: Note that I can help for this and suggest a PR.

**Comment by MatMoul** [comment]
Hi and thank you for the suggestion but I don't think it's relevant here ...

If you add archfi to the ISO, archfi will not be updated when you launch it.

And my biggest fear is to have to provide support for ArchISO ...

**Comment by roipoussiere** [comment]
> Hi and thank you for the suggestion

Hello and thank you to you for developing archi. :)

> If you add archfi to the ISO, archfi will not be updated when you launch it.
> 
> And my biggest fear is to have to provide support for ArchISO ...

Sorry I'm new to the ArchLinux community and there is a couples of things that I don't understand here. :)

- *archfi will not be updated*: so does archi have a built-in auto-update feature?
- if so, why it will not work when adding archi to the iso? My assumption were that the two methods I described led to the exact same result.
- why do you think that you will have to provide support for ArchISO? It seems obvious that ArchISO and archi are two different projects, while intrinsically related.

**Comment by MatMoul** [comment]
Hi,

archfi don't need a built-in auto-update feature because you download it each time you start the ISO...
If you wan't a binary on your ArchISO, you need to make a script that download archfi.
For Archdi, an auto-update feature is provided because you can install it on your distro.

**Comment by roipoussiere** [comment]
> archfi don't need a built-in auto-update feature because you download it each time you start the ISO...

That makes sense.

> If you wan't a binary on your ArchISO, you need to make a script that download archfi.
> For Archdi, an auto-update feature is provided because you can install it on your distro.

What I would like is to prevent the user to configure the network, which can be a tedious task that, in addition, must be done twice (one in the archiso and a second one in the actual installation).

From what you're saying, I understand that a solution could be to create a script that set keyboard map, configure the network, then download archi and execute it, which, in turn, downloads and executes archdi.

That seems a little bit complex. What do you think about adding an auto-update feature on archfi?

In this way we could add an option to archfi that helps the user to configure the network, then ask to update archi.

**Comment by MatMoul** [comment]
Archfi is intended to be used with the last ArchLinux ISO.
I can't provide update for old ISO. With ArchISO, you need to rebuild your iso each month if you want to be up to date.

Second problem is that an ISO is readonly. This require to download the last archfi in ram.

Now for the keyboard, you can easily add the `/etc/vconsole.conf` file to the ISO.

For the network, it's not very hard.
With wire, it work out the box with DHCP.
And with WIFI, you just need to launch wifi-menu.

For the user, you can edit the file `/etc/issue` to add the requiered help.

**Comment by roipoussiere** [comment]
> Archfi is intended to be used with the last ArchLinux ISO. I can't provide update for old ISO. With ArchISO, you need to rebuild your iso each month if you want to be up to date.

I understand that and it's perfectly ok, I was talking about updating archfi, not archiso. :)

> And with WIFI, you just need to launch wifi-menu.

I didn't know that command. I set wifi with [WPA_supplicant](https://wiki.archlinux.org/index.php/WPA_supplicant#Advanced_usage) and that was not really practical.

Knowing that, this issue is less relevant now, but you can eventually add one line about the network configuration in the readme, since it's a required step to get archfi.

**Comment by MatMoul** [comment]
> I understand that and it's perfectly ok, I was talking about updating archfi, not archiso. :)

Yes, the best and easy way is to add my two line in a custom script....

> I didn't know that command. I set wifi with WPA_supplicant and that was not really practical.

Try it, perhaps you need one or two params (-o or wifi device, it was long time I don't used it)

> Knowing that, this issue is less relevant now, but you can eventually add one line about the network configuration in the readme, since it's a required step to get archfi.

I'm not sur if this is very well to add network setting info herre.
Skipping this part prevent me many issue...
But adding a line that say that you need to be connected to internet before launching the script seem missing.

**Comment by roipoussiere** [comment]
> I'm not sur if this is very well to add network setting info here.

Maybe you can mention the `wifi-menu` command without adding more details (just like you did here), and add a link to an Arch wiki page like [this one](https://wiki.archlinux.org/index.php/Network_configuration)?

**Comment by MatMoul** [comment]
Ok I'll try to provide a better explain in my README...
If you have a text in the the mind you can make a PR
