### ISSUE TITLE
cryptotab typo

### ISSUE THREAD

**Issue by atommixz** [MatMoul/archfi#5]
I think it should be crypttab

**Comment by MatMoul** [comment]
Ok, but it's seem that's it, right?

**Comment by atommixz** [comment]
I think again we are experiencing the difficulties of translation. 

https://wiki.archlinux.org/index.php/Dm-crypt/System_configuration#crypttab

I mean, you need to make s/cryptotab/crypttab/ in source code.

You don't think so??

**Comment by MatMoul** [comment]
Yes, your right. I add it to the TODO list.

**Comment by MatMoul** [comment]
The new release includes these changes.
