### ISSUE TITLE
file /etc/hosts is not updated by archfi

### ISSUE THREAD

**Issue by TheLinuxNinja** [MatMoul/archfi#50]
It appears the installation step for updating the /etc/hosts file isn't in the archfi script

According to the wiki, it should be updated as so:

```
127.0.0.1	localhost
::1		localhost
127.0.1.1	myhostname.localdomain	myhostname
```

Since we already have the hostname in a var, should be easy to output this file.
If agreed upon, I can submit a PR.

**Comment by MatMoul** [comment]
I agree, I always skip this file but it's a good practice...

**Comment by MatMoul** [comment]
Comming back for this feature, we need a inputbox to choose the domain name...

**Comment by MatMoul** [comment]
After reading the network installation wiki, (https://wiki.archlinux.org/index.php/Installation_guide#Network_configuration)
it seems that an info is missing.

Looking on the network configuration wiki (https://wiki.archlinux.org/index.php/Network_configuration#Local_hostname_resolution)
it indicates that systemd is handling it now.

**Comment by TheLinuxNinja** [comment]
If you comment out the entries in /etc/hosts, then `getent hosts` returns no entries.
The comment on the page you referenced is mis-leading. You DO still need the /etc/hosts file entries for localhost. The page gives 3 scenarios of which one of them is putting your hostname in /etc/hosts, the other 2 are using DNS or using Zero Configuration networking. We never assume services outside of our local Arch install are available. Having our hostname in /etc/hosts is the least amount of work and is usually assumed for all *NIX installations. (Even Windows uses it.) I'll work on the PR.

**Comment by MatMoul** [comment]
@TheLinuxNinja You submited a good question, I learn, I learn...

After readind the manpage of hosts `man hosts`, I read it's required from some special case only (bootstrapping, NIS, isolated nodes) not an standard install....

And I've found this on the Archlinux Forum :
https://bbs.archlinux.org/viewtopic.php?id=232778
Now the NSS module of Systemd handle the resolution of the localhost and the computer hostname.

I suggest that the option in "archfi" be optional

**Comment by TheLinuxNinja** [comment]
https://github.com/MatMoul/archfi/pull/54

**Comment by MatMoul** [comment]
#54
