### ISSUE TITLE
Auto Partitions with EFI creates primary partitions 1,3,4 and skips 2

### ISSUE THREAD

**Issue by TheLinuxNinja** [MatMoul/archfi#55]
I'm going through the various options for install to look for issues we faced during the Arch Install party.

The option for 'Auto Partitions (gpt,efi)' skips partition 2.
This is confusing.

I'll test each Auto Partition option and submit a PR to correct them where needed.

**Comment by MatMoul** [comment]
The auto part was made more than 4 years ago and need to be rewrited...
My idea is to make a wizard...
I've tryed in this old branch https://github.com/MatMoul/archfi/tree/partwizard but I've missing time to finalize it...

**Comment by TheLinuxNinja** [comment]
I've also found the EFI partition isn't really being done following 'best practices'.
I'll be at SELF this weekend, but should have some time next weekend to do some testing on this.

**Comment by MatMoul** [comment]
Before working to hard on autopart...
I suggest to start to write a wizard to replace it...

**Comment by MatMoul** [comment]
Some ideas comming to me...

Providing one option with a wizard...
Providing one option with autopart...

Wizard can make custom partitions
Autopart can provide some part shemes (btrfs, ext4, lvm, luks, ...)

**Comment by TheLinuxNinja** [comment]
A wizard would be a new feature. I opened this issue to fix the existing problem. Since we seem to disagree on moving forward, I'm closing this issue.

**Comment by Anonymo** [comment]
> A wizard would be a new feature. I opened this issue to fix the existing problem. Since we seem to disagree on moving forward, I'm closing this issue.

I think he was talking about using both a wizard and autopart.

**Comment by MatMoul** [comment]
@Anonymo I understand but after some very good PR @TheLinuxNinja has closed all these work after this last comment https://github.com/MatMoul/archfi/issues/58#issuecomment-507943383
We are on Github and everyone is free to follow his way ;-)

**Comment by BL4CKH47H4CK3R** [comment]
Through fat32(efi) formatted, Grub2 can find label /boot/efi so not installing when manually done
