### ISSUE TITLE
Throughout the code, ${var//%1/text} is used, but expected output is unclear

### ISSUE THREAD

**Issue by TheLinuxNinja** [MatMoul/archfi#56]
I'm not sure what the syntax ${var//%1/text} is intended to do, but for me in both bash and zsh, it does nothing but maintain the original contents of ${var}

Can you please explain?

**Comment by MatMoul** [comment]
the ${var//%1/text} syntax is used to replace text in a variable...
I use it for translation, if you look on a language file you can view some strings with %1, the %1 is replaced bay the text string....

**Comment by TheLinuxNinja** [comment]
when I run archfi, the string substitution isn't taking place in the menus from what I can see.
maybe I'm missing something, but I suspect this isn't working as intended.
did wrapping the bash vars with {} change this?

**Comment by MatMoul** [comment]
look at line 1713
`txtautopartsconfirm="Selected device : %1\n\nAll data will be erased ! \n\nContinue ?"`
the result in archfi is that %1 is replaced by /dev/sda
