### ISSUE TITLE
first run of archfi runs pacman before sync'ing the repo db

### ISSUE THREAD

**Issue by TheLinuxNinja** [MatMoul/archfi#58]
when running archfi immediately after boot, pacman is run before the first menu without doing a 'pacman -Sy' which results in errors:

warning: database file for 'core' does not exist (use '-Sy' to download)
warning: database file for 'extra' does not exist (use '-Sy' to download)
warning: database file for 'community' does not exist (use '-Sy' to download)
error: target not found: arch-install-scripts
error: target not found: wget
error: target not found: libnewt

Installing wget is not needed since it is already installed as part of the archiso build.

Since arch-install-scripts and libnewt are never installed, I can assume they aren't needed and this line can be removed from archfi entirely. Else, this will need to be done after the mirrorlist is configured and the initial package database has been sync'd.

**Comment by MatMoul** [comment]
Not sure what the first question is?
I've never met this case and yet I test archfi every month with the new iso.
In what situation did you encounter this problem?

For arch-install-scripts, wget and libnewt, this is the dependencies of archfi...
The line is need because you can use archfi on a live USB or your own install to install an other device...
If these 3 package aren't installed, they will be installed...

**Comment by MatMoul** [comment]
I thought about this issue, and it's true that it can happen ...
But I would not like to pervert a functional system ...
I suggest adding a message that you need an up-to-date system or `pacman -Sy` cmd before installing these packages...

**Comment by TheLinuxNinja** [comment]
I guess we're having a language barrier. I was clear with the error and the output. I did not ask a question, I pointed out an error in your logic flow. You cannot run a `pacman -S` without first configuring the mirrors and running a `pacman -Sy`. It's that simple. Put a breakpoint in your code to view the output of the `pacman -S --needed arch-install-scripts wget libnewt` command before clearing the screen and presenting the 'mainmenu'. Test manually. You'll see that you're asking to unnecessarily install already installed packages as well as failing to trap the error output. Please re-read my comments. How can they be dependencies of archfi if they are never successfully installed?

I'm going to give up submitting PR's. I have a LOT of enhancements to make, but you're moving very slowly and we don't seem to agree on the technical points. If this one very obvious issue takes a month to fix, there's no hope in getting the remainder of my changes made. I will start a new project.

**Comment by MatMoul** [comment]
Sorry but I've a Job and a Life, I maintain my prjects on my free time, I'm not a machine....

I just wanted to tell you that the three dependencies are mandatory in some cases, but if you don't understand it and don't want to discuss it, it's definitely better for you to start your own script.

Good luck for the future
