### ISSUE TITLE
Signature issue

### ISSUE THREAD

**Issue by gittinitian** [MatMoul/archfi#61]
Thanks for your work on this installer.  I ran into the attached signature issue when running the Install Arch Linux pacstrap base step: `signature from <> is unknown trust` when attempting an install.  I broke out to a command line and installed and ran `pacman-key --refresh-keys` but that did not resolve the issue.  Any help would be appreciated.

![Signature_Issue](https://user-images.githubusercontent.com/16883244/60276463-47124300-98c1-11e9-9a88-9f5af92019a2.JPG)

**Comment by MatMoul** [comment]
Not sure, but for me, you use an old arch media or a bad mirror.

**Comment by gittinitian** [comment]
@MatMoul For the record, I did use the latest iso from 2019.06.01 🤷‍♂

**Comment by MatMoul** [comment]
@gittinitian I've just tested with the last media (the same as you) and it work for me...
Looking in /etc/pacman.d/mirrorlist, the first mirror is `mirror.xtom.com.hk`

**Comment by gittinitian** [comment]
@MatMoul Mirror list looked fine.  I figured it out and resolved the issue by setting the time: `timedatectl set-time "yyyy-MM-dd hh:mm:ss"` and then refreshing the keys: `pacman-key --refresh-keys`.  Script worked great after that. :+1:   Not sure why I had to do this and you didn't in testing :man_shrugging:; perhaps something to add to the scripts to make them more robust?

**Comment by MatMoul** [comment]
@gittinitian Thanks for the feedback ;-)
