### ISSUE TITLE
suggesting my ArchI0 script

### ISSUE THREAD

**Issue by SofianeHamlaoui** [MatMoul/archfi#62]
Hi ! 
i Have and automation applications installer and i want to share that with @MatMoul,
Tell me what do you think about it and if you can add that to your script or even if you suggest some changes. 
i'll be thankful  with any type of feedback ^^

ArchI0 : An ArchLinux Applications Automatic Installation Script
[https://github.com/SofianeHamlaoui/ArchI0](url)

**Comment by MatMoul** [comment]
Thanks for your issue but archfi is made to install the Arch Linux Base...
I don't want to use another script here !!!
