### ISSUE TITLE
User is created incorectly.

### ISSUE THREAD

**Issue by CatalinNic1** [MatMoul/archfi#64]
When the script creates a user like this: "useradd -m -g users -s /bin/bash some_user" which is incorrect because programs like pamac asks for root password instead of some_user password I think the user should be created like that "useradd -m -g users -G wheel -s /bin/bash some_user". Have a good day!

**Comment by MatMoul** [comment]
archfi doesn't create user...
I suspect this is an archdi-pkg discussion...
Look https://github.com/MatMoul/archdi/issues/6#issue-401266919
