### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by WarhawkYT** [MatMoul/archfi#65]
This isn’t an error but just a suggestion. If it’s possible to do, at the stage where you have the user select what kernel to use/install it’s a good idea to run grub-mkconfig after so it generates the updated configuration so for example if you install the lts kernel it will be used by default on restart.

**Comment by MatMoul** [comment]
Thanks for your suggestion.

When I install arch with arhcdi, I always use the config section of grub and run grub-mkconfig from here...

I leave this issue open for reflection

**Comment by WarhawkYT** [comment]
Yeah the reason why I mentioned it is I know most people installing arch will figure it out and know they have to remake the grub config after boot but some people might not so I just wanted to let you know if you didn’t know already.

**Comment by MatMoul** [comment]
@WarhawkYT This is why I leave the issue open, for reflection...
This issue should be archdi-pkg...

**Comment by MatMoul** [comment]
Closing...
You can follow this PR on archdi-pkg https://github.com/MatMoul/archdi-pkg/pull/36
