### ISSUE TITLE
f2fs-tools missing from File System section

### ISSUE THREAD

**Issue by osmose99** [MatMoul/archfi#66]
Could it be possible to add f2fs-tools in the File System section with the dosfstools and the others. If you partition with f2fs, there is this module missing to be able to use your partition.

By the way, thanks for this script.. Really useful!

**Comment by MatMoul** [comment]
After providing f2fs in archfi, f2fs need to be in archdi...
@osmose99 you can make a PR on archfi-pkg, or I can add it if you want

**Comment by osmose99** [comment]
Oh, sorry about that. I'll close this one and open another in archfi-pkg.
Thanks..
