### ISSUE TITLE
BTRFS subvolumes

### ISSUE THREAD

**Issue by Anonymo** [MatMoul/archfi#67]
Could an option be added to installer if installing with BTRFS to install more subvolumes at install time, like
@home
@var
@snapshots so that I can install snapper after and have snapshots like OpenSUSE?

Not sure how hard that would be to install.  I was looking at the code at line 610.

Mount the root btrfs volume mount 
`/dev/sda2 /mnt`
Create subvolume for root, home, var and one for snapshots
`btrfs subvolume create /mnt/@root`
`btrfs subvolume create /mnt/@var`
`btrfs subvolume create /mnt/@home`
`btrfs subvolume create /mnt/@snapshots`

Mount them
`umount /mnt`
`mount -o noatime,compress=lzo,space_cache,subvol=@root /dev/sda2 /mnt`
`mkdir /mnt/{boot,var,home,.snapshots}`
`mount -o noatime,compress=lzo,space_cache,subvol=@var /dev/sda2`
`/mnt/var mount -o noatime,compress=lzo,space_cache,subvol=@home /dev/sda2 /mnt/home`
`mount -o noatime,compress=lzo,space_cache,subvol=@snapshots /dev/sda2 /mnt/.snapshots`

Swap
`btrfs subvolume create /.swap`
`truncate -s 0 /.swap/swapfile`
`chattr +C /.swap/swapfile`

**Comment by MatMoul** [comment]
I'll try to provide a wizard that replace the autopart section...
But for now you can easily use CTRL+ALT+F2 to mount you own parts made frome here...
When your parts as ready and mounted to /mnt, you can make a CTRL+ALT+F1 and choose mount on the script.
If you're mounted your parts, these will be used as default.

**Comment by mirh** [comment]
Special case of #67 I guess?

**Comment by MatMoul** [comment]
Closing old issue...
