### ISSUE TITLE
Add linux-firmware install option for Navi-10 graphics cards

### ISSUE THREAD

**Issue by Vladimir-pa** [MatMoul/archfi#76]

**Comment by MatMoul** [comment]
Thanks for the issue,

linux-firmware needs to be added to my project but i don't know if it should be part of archfi or archdi.

If the installation with archfi is boot correctly in console without linux-firmware, this one must be integrated in archdi.

If some people encounter issue to boot with the new install without linux-firmware, it need to be an optional part of archfi

**Comment by Vladimir-pa** [comment]
IMO it should be added to archdi script because i've had no problem logging into tty after installing archdi and installing the linux-firmware manually so it shouldn't be a part of the archfi install

**Comment by MatMoul** [comment]
The new release include now kernel selection and linux-firmware
