### ISSUE TITLE
Install fails after reboot.  System stuck at systemd version and fsck.

### ISSUE THREAD

**Issue by spartus434** [MatMoul/archfi#78]
Scripts work fine during the install, however after reboot the system presents the starting version of systemd and does the fsck and than freezes.  Unable to control alt F1 F2 etc..  Only key strokes that work are Control Alt Del.  I tried using AUI last night and it was able to install and run fine.  I did notice that during mkinitcpio for the fallback image there are quite a few missing firmwares with ArchFI.  AUI did not have the same issue.  I don't know if that is helpful or not.  Love ArchFI, ArchDI and hope it gets working again in the future.

**Comment by MatMoul** [comment]
Thanks for your feedback, first, look at #76 , it's a possibility...

**Comment by spartus434** [comment]
Just did some Sunday tinkering and found that all I had to do was add 'linux-firmware' to the 'pacstrap base linux' command that is executed in ArchFi and everything worked perfectly.  Hope this helps.  Take care.

**Comment by domoaligato** [comment]
I would like to add that arch recently made some changes to there iso media and you might want to review the newest install guide
https://wiki.archlinux.org/index.php/Installation_guide#Install_essential_packages

**Comment by spartus434** [comment]
> I would like to add that arch recently made some changes to there iso media and you might want to review the newest install guide
> https://wiki.archlinux.org/index.php/Installation_guide#Install_essential_packages

Arch decided for some non-logical reason to remove the kernel and firmware from the base install.  It makes very little sense but, hey, whoever said the world made sense.

**Comment by MatMoul** [comment]
The new release include now kernel selection and linux-firmware
