### ISSUE TITLE
fails to install on non-formatted efi partition

### ISSUE THREAD

**Issue by negativeExponent** [MatMoul/archfi#81]
![1572482410897-104834340](https://user-images.githubusercontent.com/54053706/67909409-19fcd680-fbba-11e9-94ba-ca0b38f0b805.jpg)

I'm using single efi partition for windows and other Linux installs using grub.

UPDATE:
thanks for the reply. having intel-ucode.img too in the efi partition does the same.

**Comment by MatMoul** [comment]
Thanks for the issue, I never tested this case :(

**Comment by negativeExponent** [comment]
thanks for the reply. having intel-ucode.img too in the efi partition does the same.

**Comment by negativeExponent** [comment]
if this cant be forced to overwrite the file (or is it safe to do so). the problem might be because efi partition is by default mounted to /boot i believe. It usually instructed that EFI suppose to be mounted on /boot/efi (or EFI). that way, /boot (where this ucode stuff and vmlinuz) resides will always be clean on a new install (unless boot is mounted on an already exisiting partition.

**Comment by negativeExponent** [comment]
so sad to hear that mounting efi partition into /boot/efi will not be supported (despite this to be the norm for UEFI installs)

https://github.com/MatMoul/archfi/issues/114
