### ISSUE TITLE
Selection of mirrors by country

### ISSUE THREAD

**Issue by mipimipi** [MatMoul/archfi#82]
It would be helpful to have the possibility to select the mirrors by country - in addition to have the possibility to edit the mirrorlist in an editor.

**Comment by MatMoul** [comment]
It's not so easy, offering this option need to install some packages but available size is limited...

**Comment by mipimipi** [comment]
Maybe my proposal was not clear enough. I meant the possibility to select mirrors by country only in the installation process. That's a few lines of bash script. I did this already in my fork of archfi.

**Comment by MatMoul** [comment]
@mipimipi Sorry, I'm missunderstand your request and it's more easy with this solution ;-)
If you have a Fork ready, make a PR

**Comment by mrgreen3** [comment]
Did try to use sed to create a list of countries but command was getting very complicated. And it all depends on Arch keeping syntax the same. I find it easier to use something like rankmirrors or simply edit the mirrorlist file.

**Comment by MatMoul** [comment]
this is rankmirror that is not so easy to handle, how do you install it on ArchLinux media ?
You have ~250Mb free in root and ~1Gb in /tmp

**Comment by mrgreen3** [comment]
http://archbang.org/2019/08/31/want-more-room/
This would give you more head room for deps and possibly rankmirror.

**Comment by MatMoul** [comment]
@mrgreen3  A possible way but it's necessary to check if free RAM is available...

**Comment by mrgreen3** [comment]
Used to run ArchBang with 8g of copy on write space, should not be affected by available ram. Something I will test in a Virtual Machine

**Comment by mrgreen3** [comment]
So if I add a 1G of copy of write space I can easily install pacman-contrib (rankmirrors). Really surprised that arch media does not support a larger filespace.....

**Comment by MatMoul** [comment]
@mrgreen3 I've just tested to launch a `pacman -Sy` and `pacman -S pacman-contrib` with the last media.
Then I've launched `rankmirrors` with success without adding more space...
It seem to work as is but I remember a time when free size was more smaller...
But if you have the latest media, the mirrors are classified according to their last month's status ...
rankmirrors seem to be only usefull for old iso...

**Comment by mrgreen3** [comment]
https://wiki.archlinux.org/index.php/Mirrors#Sorting_mirrors
Wiki shows feeding rankmirrors (see link)... There is always reflector but that will bring python...
Something I would need to test. My Virtual Machine would not run at 256Mbs, tested at 512Mbs without issue.
