### ISSUE TITLE
Translation of Archfi to Arabic

### ISSUE THREAD

**Issue by mohdalawadi** [MatMoul/archfi#88]
Hello,

There is no issue with your Archfi installation, it's great.

I would like to offer translating it to Arabic as I am fluent in English and am a native speaker of the Arabic language.

I have had years of experience with open-source software and am experienced with translating from Arabic to English and vice versa.

Thank you.

To contact me further:

alawadi@protonmail.com

**Comment by MatMoul** [comment]
Thanks for your proposition, you can easily translate archfi, just look at https://github.com/MatMoul/archfi/blob/master/CONTRIBUTING.md and https://github.com/MatMoul/archfi/tree/master/lng folder (specially the README)

**Comment by MatMoul** [comment]
@mohdalawadi Your PR seem good, need you help to finalize?

**Comment by MatMoul** [comment]
PR finalized
