### ISSUE TITLE
locale.gen twice en_US after sed

### ISSUE THREAD

**Issue by ms77grz** [MatMoul/archfi#94]
as we know locale.gen contains:
# Examples:
# en_US.UTF-8
#
#en_US.UTF-8

just add # in your version sed -i '/en_US.UTF-8/s/^#//g' /etc/locale.gen and in will not touch Examples block
sed -i '/#en_US.UTF-8/s/^#//g' /etc/locale.gen

**Comment by MatMoul** [comment]
@ms77grz Thanks for the report, I work on it for the new version...

**Comment by MatMoul** [comment]
Fixed in the last release
