### ISSUE TITLE
Option to select zsh or fish instead of bash (Feature Request)

### ISSUE THREAD

**Issue by jatin-cbs** [MatMoul/archfi#95]
Many installers for arch do provide installing different shell by default it will be great to add this feature on archfi Thanks for the amazing script :)

**Comment by MatMoul** [comment]
This issue is for archdi-pkg https://github.com/MatMoul/archdi-pkg
I hope to provide this option in the future but can't find time right now :-(
Anyone can contribute to archdi-pkg and and add features :-)
