### ISSUE TITLE
HIDPI/4K Display

### ISSUE THREAD

**Issue by KarkanAlzwayed** [MatMoul/archfi#96]
I don't know if I would consider this as an issue, but I am not too good at navigating github.
I use a Dell laptop that has a 4k display. I have installed arch through this script and it was flawless. The only issue that I had is the text/font size on my screen. It was so tiny the whole time that I eventually had a headache trying to read things. It would be greatly appreciated if support for bigger fonts on 4k screens/HIDPI was included in this script automatically or as an option when starting the script.
Thank you for the hard work put into this and looking forward to using it in the near future.

**Comment by MatMoul** [comment]
Try to take a look at #37 
It's perhapse a good idea to add a -4k args that set the font...

**Comment by KarkanAlzwayed** [comment]
> Try to take a look at #37
> It's perhapse a good idea to add a -4k args that set the font...

That worked really good actually. Thank you. Arch doesn't have bigger fonts than 22. It is still small, but waaay better than before. Now I can see.

**Comment by KarkanAlzwayed** [comment]
Set font
Then get the scrip. Matt has updated it to skip the font check, so the font you chose will stick until the end.
