### ISSUE TITLE
Can't pick between installing grub in boot or efi for grub

### ISSUE THREAD

**Issue by NathanYumekoe** [MatMoul/archfi#97]
As above, it defaults to installing in /boot and i also can't mount the efi partition to /mnt/efi

**Comment by MatMoul** [comment]
No idea with these informations...
What do you try to make? How do you install ?
Please try to more describe your issue...

**Comment by Filo97** [comment]
I am dualbooting with windows. I want to mount the EFI partition not to /mnt/boot but to /mnt/boot/efi. I also want grub in the efi partition not to install to /boot but to /EFI.

**Comment by MatMoul** [comment]
Ok, archfi is an easy way to install Arch Linux.
You can choose autopart or make your custom part layout.
The solution, is to part manually with cfdisk or cgdisk, then follow the archfi install but before mount, switch to TTY2 (CTRL+F2).
Mount your parts to /mnt (/mnt/boot, /mnt/home, ...) and when you're ready, comme back to TTY1 (CTRL+F1) and go to the next step with archfi with the mount button (Your custom mount will be preserved)
After this, you can follow the next step of archfi ;-)

**Comment by Filo97** [comment]
Hello,
My biggest issue right now, while not terrible, is that the EFI partition is messy
Most Linux distros when installing their GRUB only affect the /Efi folder in the esp
But here, there are a bunch of files in the root of the ESP, causing stuff to be messy

**Comment by Filo97** [comment]
Here is what my partition should look like, after testing a bit in VirtualBox EFI mode
![image](https://user-images.githubusercontent.com/15868262/72961031-1e4b2100-3db0-11ea-8ca8-ffaf3f7af7c6.png)
and here is what it actually looks like
![image](https://user-images.githubusercontent.com/15868262/72961095-4dfa2900-3db0-11ea-8b7b-f011ff4cc0b5.png)

**Comment by MatMoul** [comment]
Looking at https://wiki.archlinux.org/index.php/EFI_system_partition#Typical_mount_points
Mounting the ESP part to /boot is the easy way for a script...
If you have better solution, you can give me the list of commands or make a PR

**Comment by negativeExponent** [comment]
this is related to my issue: https://github.com/MatMoul/archfi/issues/81

**Comment by MatMoul** [comment]
Closing old issue...
