### ISSUE TITLE
ERROR: file not found: 'fsck.btrfs'

### ISSUE THREAD

**Issue by 1una** [MatMoul/archfi#98]
I formated my drive to btrfs using archfi, and I got error messages like this when performing `pacstrap /mnt base linux firmwares`:

![VirtualBox](https://user-images.githubusercontent.com/49582915/73065098-ab3fc880-3edd-11ea-9191-034bb7bb5930.png)

It seems that we need `fsck.btrfs`. `pacman -F fsck.btrfs` tells me it belongs to `btrfs-progs`.
However, `btrfs-progs` has been included in the official Arch Linux Image. So I have no idea why this would happen.

I was using VirtualBox so it should be easy to reproduce. The Host OS is `Arch Linux` and I made little configurations to VirtualBox except *Enabling EFI*.

**Comment by MatMoul** [comment]
This is normal, at this point, btrfs-utils isn't installed.
This happens in archfi.

**Comment by 1una** [comment]
Using `pacstrap /mnt base btrfs-progs linux linux-firmware` instead of `pacstrap /mnt base linux linux-firmware` solves it. I know little about shell script so I can't open a pr, I wonder if there is a plan to fix it?

**Comment by 1una** [comment]
> Using `pacstrap /mnt base btrfs-progs linux linux-firmware` instead of `pacstrap /mnt base linux linux-firmware` solves it. I know little about shell script so I can't create a pr, wondering if there is a plan to fix it?

**Comment by 1una** [comment]
Using `pacstrap /mnt base btrfs-progs linux linux-firmware` instead of `pacstrap /mnt base linux linux-firmware` solves it. I know little about shell script so I can't create a pr, wondering if there is a plan to fix it?

**Comment by MatMoul** [comment]
It isn't so simple,
For a long time, the base group has included everything you need.
These last months, there has been a major cleaning with the replacement of the base group by the base package ...
Now I allow myself to take time to define the archfi limit (firmaware, filesystems, editors, ...)

**Comment by MatMoul** [comment]
Feature implemented...
